repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # This is the version of the hooks to use
    hooks:
    -   id: trailing-whitespace    # Removes trailing whitespace
    -   id: end-of-file-fixer      # Ensures files end with a newline
    -   id: check-yaml             # Validates YAML syntax
    -   id: check-added-large-files # Prevents giant files from being committed

-   repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
    -   id: black      # Python code formatter that enforces a consistent style

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort      # Sorts Python imports alphabetically and separates them into sections
